# Generated by Django 5.1.1 on 2024-09-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(max_length=100),
        ),
    ]
